# The log format to use - "json", "node" or "full" (default: "full")
log_format = "full"

# Directory name to store node state (default: "data")
data_directory = "data_smt_auto_prover"

# URL to connect to
da_read_from = "127.0.0.1:4141"

# URL to connect to the node
node_url = "http://localhost:4321"

# Postgres database URL for ContractListener
database_url = "postgres://postgres:postgres@localhost:5432/postgres"

# Buffer txs (min txs before proving; 0 = disable buffer-size-based flushing,
tx_buffer_size = 0

# Max transactions per proof
max_txs_per_proof = 30
tx_working_window_size = 180

# Contract name to prove
contract_name = "oranj"

# ContractListener poll interval (seconds)
contract_listener_poll_interval_secs = 5

# Idle flush interval for auto prover (seconds)
idle_flush_interval_secs = 5

rest_server_port = 4321
rest_server_max_body_size = 10485760 # 10 MB

run_admin_server = true
admin_server_port = 4322
admin_server_max_body_size = 10485760 # 10 MB
