# The log format to use - "json", "node" or "full" (default: "full")
log_format = "full"

# Directory name to store node state (default: "data")
data_directory = "data"

# URL to connect to
da_read_from = "localhost:4141"
da_fallback_addresses = ["localhost:5151", "localhost:6161", "localhost:7171"]

[gcs]
# GCS bucket info
gcs_bucket = "hyli-dev-gcs-uploader"
gcs_prefix = "local"

# GCS uploader options
save_proofs = true
save_blocks = true

max_concurrent_uploads = 1000
