# The log format to use - "json", "node" or "full" (default: "full")
log_format = "full"

# Directory name to store node state (default: "data")
data_directory = "data"

# URL to connect to
da_read_from = "localhost:4141"

[gcs]
# GCS bucket info
gcs_bucket = "testnet_proofs"
gcs_prefix = "local"

# GCS uploader options
save_proofs = true
save_blocks = true

# Batching configuration
batch_size = 1000
batch_timeout_secs = 1500
retry_attempts = 5
storage_backend = "local"
