name: "clippy"

on:
  pull_request:
    paths: ["**/*.rs"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write

env:
  CARGO_TARGET_DIR: ${{ github.workspace }}/.cache/target
  CARGO_HOME: ${{ github.workspace }}/.cache/cargo-home
  SHARED_CACHE_DIR: /home/runner/.cache/node-cache/rust

jobs:
  clippy:
    name: clippy check
    if: github.event.pull_request.draft == false
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4

      - name: Copy cache from shared storage
        run: .github/scripts/copy-cache.sh "hyli-clippy"

      # For keyring dependencies
      - run: sudo apt update && sudo apt install -y libdbus-1-dev pkg-config wget build-essential libssl-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: LoliGothick/clippy-check@master
        with:
          deny: warnings
          token: ${{ secrets.GITHUB_TOKEN }}
          options: "--workspace --all-targets -F sp1 -F risc0"
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run cargo check
        run: cargo check --workspace

      - name: Save cache to shared storage
        if: always() && github.ref == 'refs/heads/main'
        run: .github/scripts/save-cache.sh "hyli-clippy"
