name: Docker image

on:
  push:
    branches:
      - "main"
      - "releases/**"
    tags:
      - "*"
  workflow_dispatch: {}

env:
  AR_REPO_LOCATION: "europe-west1-docker.pkg.dev"

jobs:
  build_and_push:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - file: Dockerfile
            name: hyli
            push_ghcr: true
            platform: linux/amd64
            dep_image: europe-west1-docker.pkg.dev/hyli-shared-all/hyli/hyli-dependencies:main
            images: |
              europe-west1-docker.pkg.dev/hyli-shared-all/hyli/hyli
              ghcr.io/hyli-org/hyli
          - file: .github/docker/Dockerfile.arm64
            name: hyli (arm64)
            push_ghcr: true
            platform: linux/arm64
            dep_image: rust:bookworm
            images: |
              europe-west1-docker.pkg.dev/hyli-shared-all/hyli/hyli-arm
              ghcr.io/hyli-org/hyli-arm
          - file: .github/docker/Dockerfile.dependencies
            name: hyli dependencies
            push_ghcr: false
            platform: linux/amd64
            dep_image: europe-west1-docker.pkg.dev/hyli-shared-all/hyli/hyli-dependencies:main
            images: |
              europe-west1-docker.pkg.dev/hyli-shared-all/hyli/hyli-dependencies

    name: ${{ matrix.mode.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.mode.images }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/493106494045/locations/global/workloadIdentityPools/hyli-all-pool/providers/hyli-github-provider"
          service_account: "ci-builder-sa@hyli-shared-all.iam.gserviceaccount.com"

      - name: "Authenticate docker on gcp"
        run: |
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        if: ${{ matrix.mode.push_ghcr }}
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.mode.platform }}
          file: ${{ matrix.mode.file }}
          context: .
          build-args: |
            DEP_IMAGE=${{ matrix.mode.dep_image }}
            BASE_IMAGE=ghcr.io/hyli-org/base:main
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  multiplatform_image:
    needs: build_and_push
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            europe-west1-docker.pkg.dev/hyli-shared-all/hyli/hyli
            ghcr.io/hyli-org/hyli
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/493106494045/locations/global/workloadIdentityPools/hyli-all-pool/providers/hyli-github-provider"
          service_account: "ci-builder-sa@hyli-shared-all.iam.gserviceaccount.com"

      - name: "Authenticate docker on gcp"
        run: |
          gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Create multi-arch manifest
        run: |
          tags_raw="${{ steps.meta.outputs.tags }}"
          # convert newline-separated list into a bash array (tags_array) and also a space-separated string (tags) for compatibility
          mapfile -t tags_array <<< "$tags_raw"
          for tag in "${tags_array[@]}"; do
            echo "Creating manifest for $tag"
            docker buildx imagetools create -t $tag $tag $(echo "$tag" | sed 's/\/hyli:/\/hyli-arm:/g')
          done
