name: Docker image

on:
  push:
    branches:
      - "main"
      - "releases/**"
    tags:
      - "*"
  workflow_dispatch: {}

env:
  AR_REPO_LOCATION: "europe-west3-docker.pkg.dev"

jobs:
  build_and_push:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - file: Dockerfile
            name: hyli
            push_ghcr: true
            enable_cairo_m: false
            images: |
              europe-west3-docker.pkg.dev/hyle-413414/hyli-docker/hyli
              ghcr.io/hyli-org/hyli
          - file: Dockerfile
            name: hyli (cairo-m)
            push_ghcr: true
            enable_cairo_m: true
            images: |
              europe-west3-docker.pkg.dev/hyle-413414/hyli-docker/hyli-cairo-m
              ghcr.io/hyli-org/hyli-cairo-m
          - file: Dockerfile.dependencies
            name: hyli dependencies
            push_ghcr: false
            enable_cairo_m: false
            images: |
              europe-west3-docker.pkg.dev/hyle-413414/hyli-docker/hyli-dependencies

    name: ${{ matrix.mode.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.mode.images }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
          registry: ${{ env.AR_REPO_LOCATION }}

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        if: ${{ matrix.mode.push_ghcr }}
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.mode.file }}
          context: .
          build-args: |
            DEP_IMAGE=europe-west3-docker.pkg.dev/hyle-413414/hyli-docker/hyli-dependencies:main
            ENABLE_CAIRO_M=${{ matrix.mode.enable_cairo_m }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
