name: Run Turmoil Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  test-turmoil:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run turmoil tests - Basic
        run: cargo test turmoil_simulation_basic --features turmoil
      - name: Run turmoil tests - Add a node
        run: cargo test turmoil_simulation_one_more_node --features turmoil
      - name: Run turmoil tests - Hold traffic
        run: cargo test turmoil_simulation_hold --features turmoil
      - name: Run turmoil tests - Slow Network
        run: cargo test turmoil_simulation_slow_network --features turmoil
      - name: Run turmoil tests - Slow Node
        run: cargo test turmoil_simulation_slow_node --features turmoil
      - name: Run turmoil tests - 2 Slow Nodes
        run: cargo test turmoil_simulation_two_slow_nodes --features turmoil
