name: Run Turmoil Tests

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-turmoil:
    runs-on: arc-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run turmoil tests - Basic
        run: cargo test turmoil_simulation_basic --features turmoil
      - name: Run turmoil tests - Add a node
        run: cargo test turmoil_simulation_one_more_node --features turmoil
      - name: Run turmoil tests - Hold traffic
        run: cargo test turmoil_simulation_hold --features turmoil
      - name: Run turmoil tests - Slow Network
        run: cargo test turmoil_simulation_slow_network --features turmoil
      - name: Run turmoil tests - Slow Node
        run: cargo test turmoil_simulation_slow_node --features turmoil
      - name: Run turmoil tests - 2 Slow Nodes
        run: cargo test turmoil_simulation_two_slow_nodes --features turmoil
      - name: Run turmoil tests - Partition
        run: cargo test turmoil_simulation_partition --features turmoil
      - name: Run turmoil tests - Drop Storm
        run: cargo test turmoil_simulation_drop_storm --features turmoil
      - name: Run turmoil tests - Restart Node
        run: cargo test turmoil_simulation_restart_node --features turmoil
      - name: Run turmoil tests - Realistic Network
        run: cargo test turmoil_simulation_realistic_network --features turmoil
